@startuml

title Kiosko calcula deuda total de sus clientes

TestCase -> Kiosco: deudTotal(06, 2020)
Kiosco -> Cliente : deuda(06, 2020)
loop [para todo cliente]
        Kiosco -> Cliente: deuda(06, 2020)
        Cliente -> Cliente: deudaTotal(06, 2020)
        loop [para cada tx]
                Cliente -> Transaccion: deuda(06, 2020)
                Transaccion -> Producto: precioPorCantidad(cantidad)
                return cantidad * precioProducto
        end
        loop [para cada subscripcion]
                Cliente -> SubscripcionAnual: precio(06, 2020)
                SubscripcionAnual -> Producto: precioConDto( 20 )
                return (dto * precioProducto) / ( fechaHasta - fechaDesde )
        end

        Cliente -> Cliente: aplicarDto(dueudaTotal)
        return .95 * dueudaTotal
end

@enduml
